version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MysteriousMeat"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1v9opw6l873xb"
s3_prefix = "MysteriousMeat"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
